### PR TITLE
Navigation

### PR DESCRIPTION
**Pull request by digitalWestie**
Covers issues #77 and #78

### CODE REVIEW

**Comment by ldodds** [comment]
I've taken a look at this, but the interaction for the "Save & Continue" & "Save and Exit" isn't quite right.

The wireframes just have "Next question" so I guess "Save & Continue" should be renamed to that?

I understood "Save and exit" to be: stop answering questions and return to the assessment page. 

If I click on that currently it forces me to answer the current question. The form validation should only kick in if I click "Next question". The "Save and exit" button should let me cancel what I'm doing without having to answer the current question.

We want people to be able to jump out at any point because they may need to get more information in order to answer the question.

**Comment by digitalWestie** [comment]
Ah got you will rename the Save and continue. 

I misunderstood the 'Save & exit' functionality though, I understood it as "Save this answer, and go back to the assessment overview". On that note, isn't it better labelled cancel or exit?

**Comment by ldodds** [comment]
It could be called cancel/exit, but someone might think that would abort the whole assessment for that activity. I think its Save and Exit to reinforce that what they've done is persisted (even though it already is).

Lets match wireframe for now and do a pass over naming, etc later.

**Comment by digitalWestie** [comment]
Ahah, see what you mean.

**Pull request merged**
