### PR TITLE
Answers

### PR DESCRIPTION
**Pull request by digitalWestie**
Covers issues #14  and #11, allowing users to add links to answers and allowing users to revise previous answers, however does address navigation between questions.

### CODE REVIEW

**Comment by ldodds** [comment]
I had some problems testing this. The features all pass, but when I test it in the UI:

* I couldn't see a button to save a link. Hitting return answered the question and moved on, as does Save and Continue, is that expected?
* If I revisited a question, by hitting back and reloading the page I couldn't see the link or a means to delete it
* in the database, the AssessmentAnswers weren't associated with an Answer (`answer_id`) was nil (which may be the root cause)

The last bug is a problem I fixed elsewhere, looks like its resurfaced. Perhaps its caused by my not saving link correctly? It should be invalid for an AssessmentAnswer to be saved without an `answer_id`

**Comment by ldodds** [comment]
btw, `answer_id` seems to be populated if just proceed through the questions, but not if I add a link.

Also for #11 when I revised a previous answer I didn't get any kind of warning that subsequent answers would be invalidated. Looks like the answers are still in the database too. If they change to a negative answer, then all subsequent answers will need to be removed.

**Comment by digitalWestie** [comment]
To answer question, hitting return or save and continue should do the same thing. I've nested the link attributes in with the assessment answer stuff so the idea is that it all saves at once, hence no 'save link' button. Looking into the other issues now.

**Comment by digitalWestie** [comment]
EDIT: fixed problems, this now also addresses #88

**Pull request merged**
